apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: celery-beat:latest
        command: ["celery", "-A", "Epam_hacknu", "beat", "-l", "info"]
        volumeMounts:
        - name: code-volume
          mountPath: /code
      volumes:
      - name: code-volume
        persistentVolumeClaim:
          claimName: code-pvc
