version: '3.10'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=epamdb
      - POSTGRES_USER=epamuser
      - POSTGRES_PASSWORD=securepassword
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - epam

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - epam

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    networks:
      - epam
    ports:
      - '8000:8000'
    volumes:
      - .:/code
      - static_volume:/code/static

  worker:
    restart: always
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    command: celery -A Epam_hacknu worker -l info
    volumes:
      - ./:/code
    depends_on:
      - webapp
      - redis
      - postgres
    networks:
      - epam

  beat:
    restart: always
    build:
      context: .
      dockerfile: ./celery/Dockerfile
    command: celery -A Epam_hacknu beat -l info
    volumes:
      - ./:/code
    depends_on:
      - webapp
      - redis
      - worker
      - postgres
    networks:
      - epam

networks:
  epam:

volumes:
  db_data:
  static_volume: