apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: yyerss/epam_hacknu-webapp:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 2
        volumeMounts:
        - name: code-volume
          mountPath: /code
        - name: static-volume
          mountPath: /code/static
      volumes:
      - name: code-volume
        persistentVolumeClaim:
          claimName: code-pvc
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
