apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: code-volume
          mountPath: /code
        - name: static-volume
          mountPath: /code/static
      volumes:
      - name: code-volume
        persistentVolumeClaim:
          claimName: code-pvc
      - name: static-volume
        persistentVolumeClaim:
          claimName: static-pvc
