# Generated by Django 5.0.4 on 2024-04-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WordG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kazakh', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
            ],
        ),
    ]
