# Generated by Django 5.0.4 on 2024-04-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grammar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammarRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_text', models.TextField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Grammar',
        ),
        migrations.RemoveField(
            model_name='wordg',
            name='english',
        ),
        migrations.RemoveField(
            model_name='wordg',
            name='kazakh',
        ),
        migrations.AddField(
            model_name='wordg',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='wordg',
            name='english_translation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wordg',
            name='kazakh_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
