# Generated by Django 5.0.4 on 2024-04-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
