# Generated by Django 5.0.4 on 2024-04-13 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_determined_lvl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsubmission',
            name='answers',
        ),
        migrations.CreateModel(
            name='SubmissionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_determined_lvl.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_determined_lvl.question')),
            ],
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='details',
            field=models.ManyToManyField(related_name='submissions', to='test_determined_lvl.submissiondetail'),
        ),
    ]
