# Generated by Django 5.0.4 on 2024-04-13 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_determined_lvl', '0002_remove_testsubmission_answers_submissiondetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiondetail',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_details', to='test_determined_lvl.testsubmission'),
        ),
        migrations.AlterField(
            model_name='testsubmission',
            name='details',
            field=models.ManyToManyField(related_name='test_submissions', to='test_determined_lvl.submissiondetail'),
        ),
    ]
